name: "note_apps"
description: "A new Flutter project."
version: 1.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  animated_tree_view: ^2.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  watch_it: ^1.4.0
  sqflite: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  path_provider: ^2.0.2
  http: ^1.2.1
  connectivity_plus: ^6.0.2
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/design/
    - assets/icons/
    - assets/icons/tip/
    - assets/icons/note/
